In [1]:
# Instantiate the napari viewer
import napari
viewer = napari.Viewer()

In [2]:
# Read the image
from skimage.io import imread
image = imread('https://github.com/NEUBIAS/training-resources/raw/master/image_data/xy_calibrated_16bit__nuclear_protein_control.tif')

In [24]:
# Check image type and values
import numpy as np
print(image.dtype, np.min(image), np.max(image))

uint16 8 3804


In [3]:
# View the intensity image as grayscale
viewer.add_image(image, name='image_grayscale', colormap='gray')

<Image layer 'image_grayscale' at 0x1d9ba0d1940>

In [4]:
# Change brightness and contrast
viewer.layers['image_grayscale'].contrast_limits=(100, 175)

<Image layer 'image_cyan' at 0x1d9c1f940a0>

In [11]:
# chaneg colormap
print(list(napari.utils.colormaps.AVAILABLE_COLORMAPS))
viewer.add_image(image, name='image_cyan', colormap='cyan')

In [16]:
# Extract image data from the layers
image_grayscale = viewer.layers['image_grayscale']
image_cyan = viewer.layers['image_cyan']

In [22]:
# Compare raw data
print(image_grayscale.data[:5,:5])
print(image_cyan.data[:5,:5])
print((image_grayscale.data == image_cyan.data).all())

True
[[93 95 96 95 90]
 [92 91 91 89 86]
 [90 88 87 86 85]
 [88 87 86 85 85]
 [86 85 85 85 85]]
[[93 95 96 95 90]
 [92 91 91 89 86]
 [90 88 87 86 85]
 [88 87 86 85 85]
 [86 85 85 85 85]]
